language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9
env:
  - DATABASE_URL='postgres://postgres@localhost/travis_ci_test'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - cd web/
  - bundle install
  - wget http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.7-1_amd64.deb
  - sudo dpkg -i shellcheck_0.3.7-1_amd64.deb
  - sudo apt-get -y update
  - sudo apt-get -y install python-software-properties
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get -y update
  - sudo apt-get -y install python3.3
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3.3 get-pip.py
  - rm get-pip.py
  - sudo pip install pylint
script:
  - bundle exec rake db:migrate
  - bundle exec rake
