sudo: false
language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9
env:
  - DATABASE_URL='postgres://postgres@localhost/travis_ci_test'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
addons:
  apt:
    packages:
      - pylint
      - shellcheck
install:
  - cd web/
  - bundle install
script:
  - bundle exec rake db:migrate
  - bundle exec rake
